//*****************************************************************************
//*****************************************************************************
//  FILENAME: Counter8_1.h
//   Version: 2.5, Updated on 2006/05/15 at 14:57:49
//  Generated by PSoC Designer ver 4.4  b1884 : 14 Jan, 2007
//
//  DESCRIPTION: Counter8 User Module C Language interface file
//               for the 22/24/27/29xxx PSoC family of devices
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress MicroSystems 2000-2004. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <m8c.h>

#pragma fastcall16 Counter8_1_EnableInt
#pragma fastcall16 Counter8_1_DisableInt
#pragma fastcall16 Counter8_1_Start
#pragma fastcall16 Counter8_1_Stop
#pragma fastcall16 Counter8_1_bReadCounter              // Read  DR0
#pragma fastcall16 Counter8_1_WritePeriod               // Write DR1
#pragma fastcall16 Counter8_1_bReadCompareValue         // Read  DR2
#pragma fastcall16 Counter8_1_WriteCompareValue         // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 bCounter8_1_ReadCounter              // Read  DR0 (Deprecated)
#pragma fastcall16 bCounter8_1_ReadCompareValue         // Read  DR2 (Deprecated)


//-------------------------------------------------
// Prototypes of the Counter8_1 API.
//-------------------------------------------------

extern void Counter8_1_EnableInt(void);                           // Proxy Class 1
extern void Counter8_1_DisableInt(void);                          // Proxy Class 1
extern void Counter8_1_Start(void);                               // Proxy Class 1
extern void Counter8_1_Stop(void);                                // Proxy Class 1
extern BYTE Counter8_1_bReadCounter(void);                        // Proxy Class 1
extern void Counter8_1_WritePeriod(BYTE bPeriod);                 // Proxy Class 1
extern BYTE Counter8_1_bReadCompareValue(void);                   // Proxy Class 2
extern void Counter8_1_WriteCompareValue(BYTE bCompareValue);     // Proxy Class 1

// The following functions are deprecated.
// They may be omitted in future releases
//
extern BYTE bCounter8_1_ReadCounter(void);            // Deprecated
extern BYTE bCounter8_1_ReadCompareValue(void);       // Deprecated


//--------------------------------------------------
// Constants for Counter8_1 API's.
//--------------------------------------------------

#define Counter8_1_CONTROL_REG_START_BIT       ( 0x01 )
#define Counter8_1_INT_REG_ADDR                ( 0x0e1 )
#define Counter8_1_INT_MASK                    ( 0x08 )


//--------------------------------------------------
// Constants for Counter8_1 user defined values
//--------------------------------------------------

#define Counter8_1_PERIOD                      ( 0xff )
#define Counter8_1_COMPARE_VALUE               ( 0x80 )


//-------------------------------------------------
// Register Addresses for Counter8_1
//-------------------------------------------------

#pragma ioport  Counter8_1_COUNTER_REG: 0x02c              //DR0 Count register
BYTE            Counter8_1_COUNTER_REG;
#pragma ioport  Counter8_1_PERIOD_REG:  0x02d              //DR1 Period register
BYTE            Counter8_1_PERIOD_REG;
#pragma ioport  Counter8_1_COMPARE_REG: 0x02e              //DR2 Compare register
BYTE            Counter8_1_COMPARE_REG;
#pragma ioport  Counter8_1_CONTROL_REG: 0x02f              //Control register
BYTE            Counter8_1_CONTROL_REG;
#pragma ioport  Counter8_1_FUNC_REG:    0x12c              //Function register
BYTE            Counter8_1_FUNC_REG;
#pragma ioport  Counter8_1_INPUT_REG:   0x12d              //Input register
BYTE            Counter8_1_INPUT_REG;
#pragma ioport  Counter8_1_OUTPUT_REG:  0x12e              //Output register
BYTE            Counter8_1_OUTPUT_REG;
#pragma ioport  Counter8_1_INT_REG:       0x0e1            //Interrupt Mask Register
BYTE            Counter8_1_INT_REG;


//-------------------------------------------------
// Counter8_1 Macro 'Functions'
//-------------------------------------------------

#define Counter8_1_Start_M \
   Counter8_1_CONTROL_REG |=  Counter8_1_CONTROL_REG_START_BIT

#define Counter8_1_Stop_M  \
   Counter8_1_CONTROL_REG &= ~Counter8_1_CONTROL_REG_START_BIT

#define Counter8_1_EnableInt_M   \
   M8C_EnableIntMask(Counter8_1_INT_REG, Counter8_1_INT_MASK)

#define Counter8_1_DisableInt_M  \
   M8C_DisableIntMask(Counter8_1_INT_REG, Counter8_1_INT_MASK)


// end of file Counter8_1.h
