/******************************************************************************
*  Generated by PSoC Designer ver 4.4  b1884 : 14 Jan, 2007
******************************************************************************/
#include <m8c.h>
// I2CHW_1SDA address and mask defines
#pragma	ioport	I2CHW_1SDA_Data_ADDR:	0x4
BYTE			I2CHW_1SDA_Data_ADDR;
#pragma	ioport	I2CHW_1SDA_DriveMode_0_ADDR:	0x104
BYTE			I2CHW_1SDA_DriveMode_0_ADDR;
#pragma	ioport	I2CHW_1SDA_DriveMode_1_ADDR:	0x105
BYTE			I2CHW_1SDA_DriveMode_1_ADDR;
#pragma	ioport	I2CHW_1SDA_DriveMode_2_ADDR:	0x7
BYTE			I2CHW_1SDA_DriveMode_2_ADDR;
#pragma	ioport	I2CHW_1SDA_GlobalSelect_ADDR:	0x6
BYTE			I2CHW_1SDA_GlobalSelect_ADDR;
#pragma	ioport	I2CHW_1SDA_IntCtrl_0_ADDR:	0x106
BYTE			I2CHW_1SDA_IntCtrl_0_ADDR;
#pragma	ioport	I2CHW_1SDA_IntCtrl_1_ADDR:	0x107
BYTE			I2CHW_1SDA_IntCtrl_1_ADDR;
#pragma	ioport	I2CHW_1SDA_IntEn_ADDR:	0x5
BYTE			I2CHW_1SDA_IntEn_ADDR;
#define I2CHW_1SDA_MASK 0x20
#pragma	ioport	I2CHW_1SDA_MUXBusCtrl_ADDR:	0x1d9
BYTE			I2CHW_1SDA_MUXBusCtrl_ADDR;
// I2CHW_1SCL address and mask defines
#pragma	ioport	I2CHW_1SCL_Data_ADDR:	0x4
BYTE			I2CHW_1SCL_Data_ADDR;
#pragma	ioport	I2CHW_1SCL_DriveMode_0_ADDR:	0x104
BYTE			I2CHW_1SCL_DriveMode_0_ADDR;
#pragma	ioport	I2CHW_1SCL_DriveMode_1_ADDR:	0x105
BYTE			I2CHW_1SCL_DriveMode_1_ADDR;
#pragma	ioport	I2CHW_1SCL_DriveMode_2_ADDR:	0x7
BYTE			I2CHW_1SCL_DriveMode_2_ADDR;
#pragma	ioport	I2CHW_1SCL_GlobalSelect_ADDR:	0x6
BYTE			I2CHW_1SCL_GlobalSelect_ADDR;
#pragma	ioport	I2CHW_1SCL_IntCtrl_0_ADDR:	0x106
BYTE			I2CHW_1SCL_IntCtrl_0_ADDR;
#pragma	ioport	I2CHW_1SCL_IntCtrl_1_ADDR:	0x107
BYTE			I2CHW_1SCL_IntCtrl_1_ADDR;
#pragma	ioport	I2CHW_1SCL_IntEn_ADDR:	0x5
BYTE			I2CHW_1SCL_IntEn_ADDR;
#define I2CHW_1SCL_MASK 0x80
#pragma	ioport	I2CHW_1SCL_MUXBusCtrl_ADDR:	0x1d9
BYTE			I2CHW_1SCL_MUXBusCtrl_ADDR;
// LED7SEG_1a address and mask defines
#pragma	ioport	LED7SEG_1a_Data_ADDR:	0x14
BYTE			LED7SEG_1a_Data_ADDR;
#pragma	ioport	LED7SEG_1a_DriveMode_0_ADDR:	0x114
BYTE			LED7SEG_1a_DriveMode_0_ADDR;
#pragma	ioport	LED7SEG_1a_DriveMode_1_ADDR:	0x115
BYTE			LED7SEG_1a_DriveMode_1_ADDR;
#pragma	ioport	LED7SEG_1a_DriveMode_2_ADDR:	0x17
BYTE			LED7SEG_1a_DriveMode_2_ADDR;
#pragma	ioport	LED7SEG_1a_GlobalSelect_ADDR:	0x16
BYTE			LED7SEG_1a_GlobalSelect_ADDR;
#pragma	ioport	LED7SEG_1a_IntCtrl_0_ADDR:	0x116
BYTE			LED7SEG_1a_IntCtrl_0_ADDR;
#pragma	ioport	LED7SEG_1a_IntCtrl_1_ADDR:	0x117
BYTE			LED7SEG_1a_IntCtrl_1_ADDR;
#pragma	ioport	LED7SEG_1a_IntEn_ADDR:	0x15
BYTE			LED7SEG_1a_IntEn_ADDR;
#define LED7SEG_1a_MASK 0x1
#pragma	ioport	LED7SEG_1a_MUXBusCtrl_ADDR:	0x1ed
BYTE			LED7SEG_1a_MUXBusCtrl_ADDR;
// LED7SEG_1b address and mask defines
#pragma	ioport	LED7SEG_1b_Data_ADDR:	0x14
BYTE			LED7SEG_1b_Data_ADDR;
#pragma	ioport	LED7SEG_1b_DriveMode_0_ADDR:	0x114
BYTE			LED7SEG_1b_DriveMode_0_ADDR;
#pragma	ioport	LED7SEG_1b_DriveMode_1_ADDR:	0x115
BYTE			LED7SEG_1b_DriveMode_1_ADDR;
#pragma	ioport	LED7SEG_1b_DriveMode_2_ADDR:	0x17
BYTE			LED7SEG_1b_DriveMode_2_ADDR;
#pragma	ioport	LED7SEG_1b_GlobalSelect_ADDR:	0x16
BYTE			LED7SEG_1b_GlobalSelect_ADDR;
#pragma	ioport	LED7SEG_1b_IntCtrl_0_ADDR:	0x116
BYTE			LED7SEG_1b_IntCtrl_0_ADDR;
#pragma	ioport	LED7SEG_1b_IntCtrl_1_ADDR:	0x117
BYTE			LED7SEG_1b_IntCtrl_1_ADDR;
#pragma	ioport	LED7SEG_1b_IntEn_ADDR:	0x15
BYTE			LED7SEG_1b_IntEn_ADDR;
#define LED7SEG_1b_MASK 0x2
#pragma	ioport	LED7SEG_1b_MUXBusCtrl_ADDR:	0x1ed
BYTE			LED7SEG_1b_MUXBusCtrl_ADDR;
// LED7SEG_1c address and mask defines
#pragma	ioport	LED7SEG_1c_Data_ADDR:	0x14
BYTE			LED7SEG_1c_Data_ADDR;
#pragma	ioport	LED7SEG_1c_DriveMode_0_ADDR:	0x114
BYTE			LED7SEG_1c_DriveMode_0_ADDR;
#pragma	ioport	LED7SEG_1c_DriveMode_1_ADDR:	0x115
BYTE			LED7SEG_1c_DriveMode_1_ADDR;
#pragma	ioport	LED7SEG_1c_DriveMode_2_ADDR:	0x17
BYTE			LED7SEG_1c_DriveMode_2_ADDR;
#pragma	ioport	LED7SEG_1c_GlobalSelect_ADDR:	0x16
BYTE			LED7SEG_1c_GlobalSelect_ADDR;
#pragma	ioport	LED7SEG_1c_IntCtrl_0_ADDR:	0x116
BYTE			LED7SEG_1c_IntCtrl_0_ADDR;
#pragma	ioport	LED7SEG_1c_IntCtrl_1_ADDR:	0x117
BYTE			LED7SEG_1c_IntCtrl_1_ADDR;
#pragma	ioport	LED7SEG_1c_IntEn_ADDR:	0x15
BYTE			LED7SEG_1c_IntEn_ADDR;
#define LED7SEG_1c_MASK 0x4
#pragma	ioport	LED7SEG_1c_MUXBusCtrl_ADDR:	0x1ed
BYTE			LED7SEG_1c_MUXBusCtrl_ADDR;
// LED7SEG_1d address and mask defines
#pragma	ioport	LED7SEG_1d_Data_ADDR:	0x14
BYTE			LED7SEG_1d_Data_ADDR;
#pragma	ioport	LED7SEG_1d_DriveMode_0_ADDR:	0x114
BYTE			LED7SEG_1d_DriveMode_0_ADDR;
#pragma	ioport	LED7SEG_1d_DriveMode_1_ADDR:	0x115
BYTE			LED7SEG_1d_DriveMode_1_ADDR;
#pragma	ioport	LED7SEG_1d_DriveMode_2_ADDR:	0x17
BYTE			LED7SEG_1d_DriveMode_2_ADDR;
#pragma	ioport	LED7SEG_1d_GlobalSelect_ADDR:	0x16
BYTE			LED7SEG_1d_GlobalSelect_ADDR;
#pragma	ioport	LED7SEG_1d_IntCtrl_0_ADDR:	0x116
BYTE			LED7SEG_1d_IntCtrl_0_ADDR;
#pragma	ioport	LED7SEG_1d_IntCtrl_1_ADDR:	0x117
BYTE			LED7SEG_1d_IntCtrl_1_ADDR;
#pragma	ioport	LED7SEG_1d_IntEn_ADDR:	0x15
BYTE			LED7SEG_1d_IntEn_ADDR;
#define LED7SEG_1d_MASK 0x8
#pragma	ioport	LED7SEG_1d_MUXBusCtrl_ADDR:	0x1ed
BYTE			LED7SEG_1d_MUXBusCtrl_ADDR;
// LED7SEG_1e address and mask defines
#pragma	ioport	LED7SEG_1e_Data_ADDR:	0x14
BYTE			LED7SEG_1e_Data_ADDR;
#pragma	ioport	LED7SEG_1e_DriveMode_0_ADDR:	0x114
BYTE			LED7SEG_1e_DriveMode_0_ADDR;
#pragma	ioport	LED7SEG_1e_DriveMode_1_ADDR:	0x115
BYTE			LED7SEG_1e_DriveMode_1_ADDR;
#pragma	ioport	LED7SEG_1e_DriveMode_2_ADDR:	0x17
BYTE			LED7SEG_1e_DriveMode_2_ADDR;
#pragma	ioport	LED7SEG_1e_GlobalSelect_ADDR:	0x16
BYTE			LED7SEG_1e_GlobalSelect_ADDR;
#pragma	ioport	LED7SEG_1e_IntCtrl_0_ADDR:	0x116
BYTE			LED7SEG_1e_IntCtrl_0_ADDR;
#pragma	ioport	LED7SEG_1e_IntCtrl_1_ADDR:	0x117
BYTE			LED7SEG_1e_IntCtrl_1_ADDR;
#pragma	ioport	LED7SEG_1e_IntEn_ADDR:	0x15
BYTE			LED7SEG_1e_IntEn_ADDR;
#define LED7SEG_1e_MASK 0x10
#pragma	ioport	LED7SEG_1e_MUXBusCtrl_ADDR:	0x1ed
BYTE			LED7SEG_1e_MUXBusCtrl_ADDR;
// LED7SEG_1f address and mask defines
#pragma	ioport	LED7SEG_1f_Data_ADDR:	0x14
BYTE			LED7SEG_1f_Data_ADDR;
#pragma	ioport	LED7SEG_1f_DriveMode_0_ADDR:	0x114
BYTE			LED7SEG_1f_DriveMode_0_ADDR;
#pragma	ioport	LED7SEG_1f_DriveMode_1_ADDR:	0x115
BYTE			LED7SEG_1f_DriveMode_1_ADDR;
#pragma	ioport	LED7SEG_1f_DriveMode_2_ADDR:	0x17
BYTE			LED7SEG_1f_DriveMode_2_ADDR;
#pragma	ioport	LED7SEG_1f_GlobalSelect_ADDR:	0x16
BYTE			LED7SEG_1f_GlobalSelect_ADDR;
#pragma	ioport	LED7SEG_1f_IntCtrl_0_ADDR:	0x116
BYTE			LED7SEG_1f_IntCtrl_0_ADDR;
#pragma	ioport	LED7SEG_1f_IntCtrl_1_ADDR:	0x117
BYTE			LED7SEG_1f_IntCtrl_1_ADDR;
#pragma	ioport	LED7SEG_1f_IntEn_ADDR:	0x15
BYTE			LED7SEG_1f_IntEn_ADDR;
#define LED7SEG_1f_MASK 0x20
#pragma	ioport	LED7SEG_1f_MUXBusCtrl_ADDR:	0x1ed
BYTE			LED7SEG_1f_MUXBusCtrl_ADDR;
// LED7SEG_1g address and mask defines
#pragma	ioport	LED7SEG_1g_Data_ADDR:	0x14
BYTE			LED7SEG_1g_Data_ADDR;
#pragma	ioport	LED7SEG_1g_DriveMode_0_ADDR:	0x114
BYTE			LED7SEG_1g_DriveMode_0_ADDR;
#pragma	ioport	LED7SEG_1g_DriveMode_1_ADDR:	0x115
BYTE			LED7SEG_1g_DriveMode_1_ADDR;
#pragma	ioport	LED7SEG_1g_DriveMode_2_ADDR:	0x17
BYTE			LED7SEG_1g_DriveMode_2_ADDR;
#pragma	ioport	LED7SEG_1g_GlobalSelect_ADDR:	0x16
BYTE			LED7SEG_1g_GlobalSelect_ADDR;
#pragma	ioport	LED7SEG_1g_IntCtrl_0_ADDR:	0x116
BYTE			LED7SEG_1g_IntCtrl_0_ADDR;
#pragma	ioport	LED7SEG_1g_IntCtrl_1_ADDR:	0x117
BYTE			LED7SEG_1g_IntCtrl_1_ADDR;
#pragma	ioport	LED7SEG_1g_IntEn_ADDR:	0x15
BYTE			LED7SEG_1g_IntEn_ADDR;
#define LED7SEG_1g_MASK 0x40
#pragma	ioport	LED7SEG_1g_MUXBusCtrl_ADDR:	0x1ed
BYTE			LED7SEG_1g_MUXBusCtrl_ADDR;
// LED7SEG_1dp address and mask defines
#pragma	ioport	LED7SEG_1dp_Data_ADDR:	0x14
BYTE			LED7SEG_1dp_Data_ADDR;
#pragma	ioport	LED7SEG_1dp_DriveMode_0_ADDR:	0x114
BYTE			LED7SEG_1dp_DriveMode_0_ADDR;
#pragma	ioport	LED7SEG_1dp_DriveMode_1_ADDR:	0x115
BYTE			LED7SEG_1dp_DriveMode_1_ADDR;
#pragma	ioport	LED7SEG_1dp_DriveMode_2_ADDR:	0x17
BYTE			LED7SEG_1dp_DriveMode_2_ADDR;
#pragma	ioport	LED7SEG_1dp_GlobalSelect_ADDR:	0x16
BYTE			LED7SEG_1dp_GlobalSelect_ADDR;
#pragma	ioport	LED7SEG_1dp_IntCtrl_0_ADDR:	0x116
BYTE			LED7SEG_1dp_IntCtrl_0_ADDR;
#pragma	ioport	LED7SEG_1dp_IntCtrl_1_ADDR:	0x117
BYTE			LED7SEG_1dp_IntCtrl_1_ADDR;
#pragma	ioport	LED7SEG_1dp_IntEn_ADDR:	0x15
BYTE			LED7SEG_1dp_IntEn_ADDR;
#define LED7SEG_1dp_MASK 0x80
#pragma	ioport	LED7SEG_1dp_MUXBusCtrl_ADDR:	0x1ed
BYTE			LED7SEG_1dp_MUXBusCtrl_ADDR;
