/******************************************************************************
*  Generated by PSoC Designer ver 4.4  b1884 : 14 Jan, 2007
******************************************************************************/
#include "ADCINC12_1.h"
#include "Counter8_1.h"
#include "I2CHW_1Common.h"
#include "I2CHW_1Slave.h"
#include "LED7SEG_1.h"
#include "PGA_1.h"
